[build.environment]
HUGO_VERSION = "0.143.1"
NODE_VERSION = "22"
TZ = "Asia/Singapore"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production]
command = "hugo --minify --baseURL https://weeks.hsyam.com/"

[context.deploy-preview]
command = "hugo --baseURL $DEPLOY_PRIME_URL"
